### PR TITLE
[PMON] Remove ethtool form pmon docker

### PR DESCRIPTION
**Pull request by keboliu**
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

### CODE REVIEW

**Comment by keboliu** [comment]
CI Pass

**Review by Junchao-Mellanox — COMMENTED** [review]
I see in platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py, there is comment about ethtool, do we want to remove it also?

**Comment by keboliu** [comment]
> I see in platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py, there is comment about ethtool, do we want to remove it also?

will take a look, and seems with the change the ethtool will also be removed from host side, this is not what I wanted, may need further change.

**Comment by liat-grozovik** [comment]
@keboliu  there is a typo in the subject :-) please fix before upstream
'form' to 'from'

**Pull request closed without merging**
